name: Build and Deploy

on:
  push:
    branches:
      - master
      - gh-actions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: NPM install and build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: Azure Login
      uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Clean File Destination
      run: az storage blob delete-batch -s \$web --account-name ${{ secrets.STORAGE_ACCOUNT }}
    
    - name: Deploy Updated Files
      run: az storage blob upload-batch --source ${GITHUB_WORKSPACE}/public --destination \$web --account-name ${{ secrets.STORAGE_ACCOUNT }}

    - name: Purge and Refresh CDN
      run: az cdn endpoint purge --name ${{ secrets.STORAGE_ACCOUNT }} --resource-group ${{ secrets.RESOURCE_GROUP }} --profile-name ${{ secrets.CDN_PROFILE_NAME }} --content-paths '/*'
