name: Build and Deploy

on:
  push:
    branches:
      - gh-actions

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and build
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true

    - name: azure login
      uses: azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: clean file destination
      run: az storage blob delete-batch -s \$web --account-name ${{ secrets.STORAGE_ACCOUNT }}
    
    - name: deploy website
      run: az storage blob upload-batch --source ${GITHUB_WORKSPACE}/public --destination \$web --account-name ${{ secrets.STORAGE_ACCOUNT }}
